In [2]:
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
df = pd.read_csv("../data/raw/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
features = ["Pclass", "Sex", "Age", "Fare", "Embarked"]
target = "Survived"

X = df[features]
y = df[target]

X[:10]

   Pclass     Sex   Age     Fare Embarked
0       3    male  22.0   7.2500        S
1       1  female  38.0  71.2833        C
2       3  female  26.0   7.9250        S
3       1  female  35.0  53.1000        S
4       3    male  35.0   8.0500        S
5       3    male   NaN   8.4583        Q
6       1    male  54.0  51.8625        S
7       3    male   2.0  21.0750        S
8       3  female  27.0  11.1333        S
9       2  female  14.0  30.0708        C

In [ ]:
numeric_features = ["Pclass", "Age", "Fare"]
categorical_features = ["Sex", "Embarked"]

In [ ]:
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

In [ ]:
categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore")),
])

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [ ]:
logreg_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])

In [ ]:
logreg_scores = cross_val_score(
    logreg_model,
    X,
    y,
    cv=5,
    scoring="accuracy"
)
logreg_scores

print(f"LogReg mean accuracy: {logreg_scores.mean():.4f}")
print(f"LogReg std accuracy : {logreg_scores.std():.4f}")

In [ ]:
tree_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", DecisionTreeClassifier(random_state=42))
])

In [ ]:
tree_scores = cross_val_score(
    tree_model,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print(f"LogReg mean accuracy: {tree_scores.mean():.4f}")
print(f"LogReg std accuracy : {tree_scores.std():.4f}")

In [ ]:
rf_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(random_state=42)),
])

In [ ]:
rf_scores = cross_val_score(
    rf_model,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print(f"LogReg mean accuracy: {rf_scores.mean():.4f}")
print(f"LogReg std accuracy : {rf_scores.std():.4f}")

In [ ]:
results = pd.DataFrame({
    "model": ["LogisticRegression", "DecisionTree", "RandomForest"],
    "mean_accuracy": [logreg_scores.mean(), tree_scores.mean(), rf_scores.mean()],
    "std_accuracy": [logreg_scores.std(), tree_scores.std(), rf_scores.std()]

})

results.sort_values("mean_accuracy", ascending=False)

In [62]:
# Task A
features = ["Pclass", "Sex", "Age", "Fare", "Embarked"]
target = "Survived"

X = df[features]
y = df[target]

numeric_features = ["Pclass",  "Age", "Fare"]
categorical_features = ["Sex", "Embarked"]

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
    ("num", numeric_transformer, numeric_features),
    ("cat", categorical_transformer, categorical_features)
])

In [63]:
# Task B
logreg_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])

tree_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", DecisionTreeClassifier(random_state=42))
])
rf_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(random_state=42))
])

In [66]:
# Task C
logreg_scores = cross_val_score(
    logreg_model,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

tree_scores = cross_val_score(
    tree_model,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

rf_scores = cross_val_score(
    rf_model,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

In [67]:
# Task D
print(f"logreg mean - {logreg_scores.mean():.4f}\nlogreg std -{logreg_scores.std():.4f}")
print(f"decision tree mean - {tree_scores.mean():.4f}\ntree std - {tree_scores.std():.4f}")
print(f"random forest mean - {rf_scores.mean():.4f}\nrf std - {rf_scores.std():.4f}")

logreg mean - 0.7800
logreg std -0.0081
decision tree mean - 0.7778
tree std - 0.0377
random forest mean - 0.8059
rf std - 0.0191

In [61]:
# Task E
results = pd.DataFrame({
    "model": ["LogisticRegression", "DecisionTreeClassifier", "RandomForestClassifier"],
    "mean_accuracy": [logreg_scores.mean(), tree_scores.mean(), rf_scores.mean()],
    "std_accuracy": [logreg_scores.std(), tree_scores.std(), rf_scores.std()],
}
)

results.sort_values("mean_accuracy", ascending=False)

                    model  mean_accuracy  std_accuracy
2  RandomForestClassifier       0.805857      0.019100
0      LogisticRegression       0.780026      0.008134
1  DecisionTreeClassifier       0.777829      0.037666

## Выводы

- Модели нужно сравнивать в одинаковых условиях.
- Cross-validation даёт более надёжную оценку, чем один train/test split.
- Mean accuracy показывает средний уровень качества.
- Std accuracy показывает стабильность модели между фолдами.
- Лучшая baseline-модель — не всегда та, у которой просто максимальная одна цифра.